apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: dev-env-cache
  name: dev-env-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dev-env-cache
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/ms-network: "true"
        io.kompose.service: dev-env-cache
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          image: bitnami/redis:latest
          name: dev-env-cache
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
