version: "3"

services:
  dev_env_cache:
    container_name: dev_env_cache
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes  
    restart: always
    networks:
      - ms-network
  frontend:
   image: shyamkira/frontend
   container_name: frontend
   stdin_open: true
   build: ../frontend/frontend/
   ports: 
     - "3000:3000"
   networks:
     - ms-network
  #  volumes:
  #    - ../frontend/frontend:/usr/src/app
  ielts:
    image: shyamkira/ielts
    build: ./micro-services/ielts/
    container_name: ielts
    ports:
      - "4955:4955"
    networks:
      - ms-network
    # volumes:
    #  - ./micro-services/ielts:/usr/src/app    
  user-profile:
    image: shyamkira/user-profile
    container_name: user-profile
    build: ./micro-services/user-profile/
    ports:
      - "5545:5545"
    networks:
      - ms-network      
    # volumes:
    #  - ./micro-services/user-profile:/usr/src/app
  gre:
    image: shyamkira/gre
    build: ./micro-services/gre/
    container_name: gre 
    ports:
      - "6545:6545"
    networks:
      - ms-network
    # volumes:
    #  - ./micro-services/gre:/usr/src/app   
  todos:
    image: shyamkira/todos
    container_name: todos
    build: ./micro-services/todos/
    ports:
      - "7545:7545"
    networks:
      - ms-network
    depends_on: 
      - dev_env_cache
    # volumes:
    #  - ./micro-services/todos:/usr/src/app  
  feedback:
    image: shyamkira/feedback
    container_name: feedback
    build: ./micro-services/feedback/
    ports:
      - "4545:4545"
    networks:
      - ms-network
    # volumes:
    #  - ./micro-services/feedback:/usr/src/app          
  gateway:
    image: shyamkira/gateway
    container_name: gateway 
    build: ./api-gateway/
    ports:
      - "8000:8000"
    networks:
      - ms-network
    # volumes:
    #  - ./api-gateway:/usr/src/app                 
networks:
  ms-network:
    driver: bridge
    