apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ielts
  name: ielts
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ielts
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/ms-network: "true"
        io.kompose.service: ielts
    spec:
      containers:
        - image: shyamkira/ielts
          name: ielts
          ports:
            - containerPort: 4955
          resources: {}
      restartPolicy: Always
status: {}
