apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: user-profile
  name: user-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-profile
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/ms-network: "true"
        io.kompose.service: user-profile
    spec:
      containers:
        - image: shyamkira/user-profile
          name: user-profile
          ports:
            - containerPort: 5545
          resources: {}
      restartPolicy: Always
status: {}
