http:
  port: 8000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  feedback:
    host: localhost
    paths: "/feedback"
  ielts:
    host: localhost
    paths: "/ielts/*"
  user:
    host: localhost
    paths: "/user/*"
  gre:
    host: localhost
    paths: "/gre/*"
  todos:
    host: localhost
    paths: "/todos/*"    
serviceEndpoints:
  feedbackhttpbin:
    url: "http://localhost:4545"
  ieltshttpbin:
    url: "http://localhost:4955"
  userhttpbin:
    url: "http://localhost:5545"
  grehttpbin:
    url: "http://localhost:7545"
  todoshttpbin:
    url: "http://localhost:6545"    
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - default:
    apiEndpoint:
      - feedback
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      #- key-auth:
      - rate-limit:
          - action:
              max: 30
              rateLimitBy: "${req.hostname}"
      - proxy:
          - action:
              serviceEndpoint: feedbackhttpbin
              changeOrigin: true
  - ielts:
    apiEndpoint:
      - ielts
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      #- key-auth:
      - rate-limit:
          - action:
              max: 40000
              rateLimitBy: "${req.hostname}"
      - proxy:
          - action:
              serviceEndpoint: ieltshttpbin
              changeOrigin: true
  - user:
    apiEndpoint:
      - user
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      #- key-auth:
      - rate-limit:
          - action:
              max: 50000
              rateLimitBy: "${req.hostname}"
      - proxy:
          - action:
              serviceEndpoint: userhttpbin
              changeOrigin: true
  - gre:
    apiEndpoint:
      - gre
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      #- key-auth:
      - rate-limit:
          - action:
              max: 40000
              rateLimitBy: "${req.hostname}"
      - proxy:
          - action:
              serviceEndpoint: grehttpbin
              changeOrigin: true
  - todos:
    apiEndpoint:
      - todos
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      #- key-auth:
      - rate-limit:
          - action:
              max: 40000
              rateLimitBy: "${req.hostname}"
      - proxy:
          - action:
              serviceEndpoint: todoshttpbin
              changeOrigin: true              
