apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: gre
  name: gre
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gre
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/ms-network: "true"
        io.kompose.service: gre
    spec:
      containers:
        - image: shyamkira/gre
          name: gre
          ports:
            - containerPort: 6545
          resources: {}
      restartPolicy: Always
status: {}
